$axure.loadCurrentPage({
  "url":"更新记录_4_7.html",
  "generationDate":new Date(1460019144217.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"959012ffb3164be5a9ef34f72c0cb12a",
    "type":"Axure:Page",
    "name":"更新记录 4.7",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ba3fd99158da4520a1669cf8f1396bb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":52},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1cedc5949944cc78232999cafd78d19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":52},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ccf3f061008447c854444079b42c824",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":108,
              "y":124},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6463b8161b264ef4af99f86a25db6a54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":124},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"620ad02e54934a509399354ea84cbb2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":160,
              "y":160},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d58def7fbf94141868edd07dbbeda34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":160,
                  "y":160},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcfc4f764fa94df5b5c1c272c5f59f1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":160,
              "y":186},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4158a9fa1f443718ebba67c8b95ffda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":160,
                  "y":186},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6537dcb8b85545dab8987832b738b70b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":160,
              "y":212},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d742575670d6440aa7839d45ef6ee0e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":160,
                  "y":212},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"305238ca01b44525a2263d159efd73af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":160,
              "y":238},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38fb3c05ef494537b0a111c169485fc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":160,
                  "y":238},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7e305c4a0f74653864e459ac313d407",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":390,
              "y":160},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fd19ddce08e48f68e5c46e398dd607b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":160},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 03-01&nbsp; 活动首页最新",
                      "target":{
                        "targetType":"page",
                        "url":"03-01__活动首页最新.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46375ad96917492ebee840150e933bdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":450,
              "y":186},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"194459f6b57c4cad8226053d7a01f266",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":186},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 03-01&nbsp; 活动首页最新",
                      "target":{
                        "targetType":"page",
                        "url":"03-01__活动首页最新.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e87c51cb31d94210bb12ca3a94e437d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":360,
              "y":212},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9145caab4b5a4b619f1879d00a6d10a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":212},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 03-01&nbsp; 活动首页最新",
                      "target":{
                        "targetType":"page",
                        "url":"03-01__活动首页最新.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4005446388214b1485dcf491d37b3b2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":360,
              "y":238},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7481468e375a441cbe39403714defc57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":238},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 03-06 游戏活动快讯分享页面",
                      "target":{
                        "targetType":"page",
                        "url":"03-06_游戏活动快讯分享页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ba3fd99158da4520a1669cf8f1396bb9":{
      "scriptId":"u0"},
    "e1cedc5949944cc78232999cafd78d19":{
      "scriptId":"u1"},
    "9ccf3f061008447c854444079b42c824":{
      "scriptId":"u2"},
    "6463b8161b264ef4af99f86a25db6a54":{
      "scriptId":"u3"},
    "620ad02e54934a509399354ea84cbb2e":{
      "scriptId":"u4"},
    "1d58def7fbf94141868edd07dbbeda34":{
      "scriptId":"u5"},
    "fcfc4f764fa94df5b5c1c272c5f59f1e":{
      "scriptId":"u6"},
    "c4158a9fa1f443718ebba67c8b95ffda":{
      "scriptId":"u7"},
    "6537dcb8b85545dab8987832b738b70b":{
      "scriptId":"u8"},
    "d742575670d6440aa7839d45ef6ee0e7":{
      "scriptId":"u9"},
    "305238ca01b44525a2263d159efd73af":{
      "scriptId":"u10"},
    "38fb3c05ef494537b0a111c169485fc8":{
      "scriptId":"u11"},
    "b7e305c4a0f74653864e459ac313d407":{
      "scriptId":"u12"},
    "4fd19ddce08e48f68e5c46e398dd607b":{
      "scriptId":"u13"},
    "46375ad96917492ebee840150e933bdb":{
      "scriptId":"u14"},
    "194459f6b57c4cad8226053d7a01f266":{
      "scriptId":"u15"},
    "e87c51cb31d94210bb12ca3a94e437d6":{
      "scriptId":"u16"},
    "9145caab4b5a4b619f1879d00a6d10a7":{
      "scriptId":"u17"},
    "4005446388214b1485dcf491d37b3b2c":{
      "scriptId":"u18"},
    "7481468e375a441cbe39403714defc57":{
      "scriptId":"u19"}}});