$axure.loadCurrentPage({
  "url":"03-05_官方活动分享页面.html",
  "generationDate":new Date(1460019147346.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"56dfd455d0c64b87ba58a0a7ddd01242",
    "type":"Axure:Page",
    "name":"03-05 官方活动分享页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"433c9ae6bdb1476483f2fb8bfcc0b78c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":426,
              "y":101}},
          "adaptiveStyles":{
},
          "masterId":"4e436cfc9c4c495985b56bfc5dce0d62"},
{
          "id":"7032af316b1d4984b72b1ba3d106920a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":144},
            "size":{
              "width":40,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b273a89987c496087b32434c5b1407a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":144},
                "size":{
                  "width":40,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-02_官方活动详情页面/u3.png"}},
{
          "id":"468e0163b2514f71a169c59e9d3a5bcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":151},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a4d79f84b454265a4bf3a533f45a020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":151},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f38b5b08fed44b469efb70ee5b71140a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":433,
              "y":186},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/03-01__活动首页最新/u45_line.png"}},
{
          "id":"55a111c3cd8c41dfb89ebcc09b8d33d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":442,
              "y":206},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"890641c13d944614ac52f48e5607677f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":442,
                  "y":206},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b85adee03c04704a062281bc410be6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":442,
              "y":238},
            "size":{
              "width":54,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c7c3af336b34c3fa84292fea8b64a4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":442,
                  "y":238},
                "size":{
                  "width":54,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"158540089879478592237fb0c0750687",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":654,
              "y":238},
            "size":{
              "width":42,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cef962d2603c4c0c9c1483c3acbc2e86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":654,
                  "y":238},
                "size":{
                  "width":42,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d18ccfd6586f4fcead73fd50366e810e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":720,
              "y":238},
            "size":{
              "width":36,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ecf73569ce74bb58d4717ed5332bda6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":720,
                  "y":238},
                "size":{
                  "width":36,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66a730bba4034e588d6775d2ad00b3d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":277},
            "size":{
              "width":314,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2644675cd0134726ad7b26286b61fa08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":277},
                "size":{
                  "width":314,
                  "height":94}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9089f2cf58a74da49a1a7d9a286c5603",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":441,
              "y":373},
            "size":{
              "width":144,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"183a644fbc53488082e5cb51ce77b805",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":441,
                  "y":373},
                "size":{
                  "width":144,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-02_官方活动详情页面/u18.png"}},
{
          "id":"97140e19064e4c0484a96676654a0b48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":28,
              "y":101},
            "size":{
              "width":263,
              "height":135}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2559e38cdba14f75ad962779e1f16cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":28,
                  "y":101},
                "size":{
                  "width":263,
                  "height":135}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-05_官方活动分享页面/u20.png"}},
{
          "id":"436548b5b9a0462a9733460b5e74b4bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":41,
              "y":114},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbca6bcff2394d8aa1777530c2e3cb9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":41,
                  "y":114},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38367a349c95437aa8e27fc5bdc3a4be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":153},
            "size":{
              "width":60,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fd4afd7a7384816bb07b71f718a0805",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":153},
                "size":{
                  "width":60,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-05_官方活动分享页面/u24.png"}},
{
          "id":"1749918d724c4bedacd4c8155d10ab0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":123,
              "y":158},
            "size":{
              "width":82,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4c787f1cb1548d6801431bf1a1a3385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":123,
                  "y":158},
                "size":{
                  "width":82,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d792747dca32462da18b8cbe0e79b3af",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":36,
              "y":246},
            "size":{
              "width":47,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b3f710b577a4d67ad069e81d311295a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":36,
                  "y":246},
                "size":{
                  "width":47,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c96174c2442346cd88ff19d23e9962e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":426,
              "y":657},
            "size":{
              "width":360,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd1a7fd48160435d94a9dc9e44a08fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":426,
                  "y":657},
                "size":{
                  "width":360,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-05_官方活动分享页面/u30.png"}},
{
          "id":"e0159710c3b441cf9be34bce5af2202a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":506,
              "y":670},
            "size":{
              "width":200,
              "height":41}},
          "adaptiveStyles":{
}},
{
          "id":"295cb76f5a4649ce8ec00a4a947a22c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":28,
              "y":60},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f5057bb0d8449b38d799d15ba26ebbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":28,
                  "y":60},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79c5968e9bc94cfeb9e4833f8e1f1904",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":426,
              "y":60},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24102c950a024ee2b2623afb17da9aee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":426,
                  "y":60},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c19a2bab2454f9a8cb7d2f964de3bab",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":0,
              "y":789},
            "borderWidth":"2",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8945bd664a44f0a153f60e26861e20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":0,
                  "y":789},
                "borderWidth":"2",
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"188c97b511a143668c078b843d04506d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":10,
              "y":809},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c59829cf40c43c1a5ee0b4575aacd47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":10,
                  "y":809},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u234.png"}},
{
          "id":"1151ae9790a3453a90aeeaef47db026c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":800,
              "y":809},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72b5aca8e92944168d161888cce691f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":800,
                  "y":809},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u234.png"}},
{
          "id":"18a479777e194392b69564860863d094",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":10,
              "y":860},
            "size":{
              "width":263,
              "height":135}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3163df44b7784448b0dfb8c873d3dd6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":10,
                  "y":860},
                "size":{
                  "width":263,
                  "height":135}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-05_官方活动分享页面/u20.png"}},
{
          "id":"352a88a95f09467c8d3ab510fae3702c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":23,
              "y":873},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9f059a2843d4bb69cecdadd1cf3328d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":23,
                  "y":873},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b106b3ecd1b43f4981141034afb3aa0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":912},
            "size":{
              "width":60,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5c37806f2ae47c8b5e94986d38f32eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":912},
                "size":{
                  "width":60,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-05_官方活动分享页面/u24.png"}},
{
          "id":"2bf1e0fb56d84aef9b31d5e7ac784c0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":105,
              "y":917},
            "size":{
              "width":82,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"792de5e226664c85a88349112dd89260",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":105,
                  "y":917},
                "size":{
                  "width":82,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e179bb00cc7b47db970b8666c0f68a19",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":18,
              "y":1005},
            "size":{
              "width":47,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01181fe959924aad8bbe04bcb52dd6ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":18,
                  "y":1005},
                "size":{
                  "width":47,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f77ae5d0e7794ada92151af96338b944",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":895},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"309cd05fb6614600af6626a0dfbf1def",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":895},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"2156d6aa2b434cfc83dc05291b505f56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":407,
              "y":884},
            "size":{
              "width":89,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88772de1a2e84c1d8acda4ed4a4ba00e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":884},
                "size":{
                  "width":89,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8ec4ea9f27e413f9b15cbd0eab35e3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":351,
              "y":884},
            "size":{
              "width":46,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32ac9548a6344905bf9c9433cc307136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":351,
                  "y":884},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f162c6924364b9bb2520a59287c6f1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":407,
              "y":920},
            "size":{
              "width":89,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"104555be94e749eab9763d8487fa6df3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":920},
                "size":{
                  "width":89,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98ef28a013f34488bbcfc552ddaad5d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":407,
              "y":956},
            "size":{
              "width":89,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27435028e0a545c3a993336efcf73c75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":956},
                "size":{
                  "width":89,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25e544b13e1c4082b20384dbcf952a0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":441,
              "y":988},
            "size":{
              "width":44,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64d41ee861784d688f85cd3b586aca87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":441,
                  "y":988},
                "size":{
                  "width":44,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c36828e39d4546ce9ff3dc08510dbfe9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":485,
              "y":988},
            "size":{
              "width":255,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b5665617cb04225a614006307e52169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":485,
                  "y":988},
                "size":{
                  "width":255,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a200fa7590047a1ad4552acbe4bb475",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":485,
              "y":1018},
            "size":{
              "width":305,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bee4a14dfc4c4511bf88793f05052b50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":485,
                  "y":1018},
                "size":{
                  "width":305,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cb913e6a2374526bcbe8cae6a467edb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1162}},
          "adaptiveStyles":{
},
          "masterId":"4e436cfc9c4c495985b56bfc5dce0d62"},
{
          "id":"0a40b090891f415aae6c48765cf614e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":1174},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ce09003c477403f96c3bd0f1994a54d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":1174},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38f69ba9b3ec4ac39c75174d96514c3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1205},
            "size":{
              "width":40,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c72cdc51de941cca9da88fe0aa6673b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1205},
                "size":{
                  "width":40,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-02_官方活动详情页面/u3.png"}},
{
          "id":"d93eb6054b2944f3a80992975a18c043",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":326,
              "y":1174},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0464339474a4b08b405e5e3f38da7d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":326,
                  "y":1174},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b9fea648cad4a80811f5c18001c84ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":1212},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe28307c68a43bfb73f67aca0500454",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":1212},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ff2e398dc8c4e2799109b0575f3545b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":1247},
            "size":{
              "width":340,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/03-01__活动首页最新/u45_line.png"}},
{
          "id":"2b35cef5f0834ba8bb8d4b197b77f156",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":26,
              "y":1267},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"988d44c99b1d42fcb6778816596ff7e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":26,
                  "y":1267},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"474421a6570d4a5ea5f7de3e17e5e110",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":26,
              "y":1299},
            "size":{
              "width":54,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9e7e461aedb483d99e1c7db4389ad12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":26,
                  "y":1299},
                "size":{
                  "width":54,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad3f6509b1984972889e8fac54e6c1aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":238,
              "y":1299},
            "size":{
              "width":42,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f6854a4984849c78ab24b9ae12c6d8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":238,
                  "y":1299},
                "size":{
                  "width":42,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef12d1f7fe3d415ea740dba9a5aed999",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":304,
              "y":1299},
            "size":{
              "width":36,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfe09d6de32244289a6072f1b531d165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":1299},
                "size":{
                  "width":36,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7932505879c34a2fbee9b15d7e620227",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":1338},
            "size":{
              "width":314,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26e5f73b126d43a78ff97a2c7137ced8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":1338},
                "size":{
                  "width":314,
                  "height":94}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f0b9fd2a6f24840b67e1d77a6ba2637",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":1434},
            "size":{
              "width":144,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"965a68c25e6b402b8a88e6559dc91a3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":1434},
                "size":{
                  "width":144,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-02_官方活动详情页面/u18.png"}},
{
          "id":"969e57dfe5944090b97ba1dd89a00374",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":10,
              "y":1718},
            "size":{
              "width":360,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61cb2b9955d241ca9296c25e4d581a56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":10,
                  "y":1718},
                "size":{
                  "width":360,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-05_官方活动分享页面/u30.png"}},
{
          "id":"6e2301363d0b455b98731bcdedf04ffd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":90,
              "y":1731},
            "size":{
              "width":200,
              "height":41}},
          "adaptiveStyles":{
}},
{
          "id":"2dea9b0dccf44d5c89d717c34189f11c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":1364},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb5528f0ecbf4ec2a6c052b8c2ffce81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":1364},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"1a3db5dd41ac456fb115f3c6c2ec9562",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":504,
              "y":1353},
            "size":{
              "width":260,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f62f2075952645bc87e9ff40d54f4b84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":504,
                  "y":1353},
                "size":{
                  "width":260,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f61e5d637cdf49caa507541071c97b0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":448,
              "y":1353},
            "size":{
              "width":46,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c841e16a9f8041dd91fefc8eddc4e921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":448,
                  "y":1353},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c38278e33f14ef9add42dcf5af80920",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":1751.5},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43ce57e3f078483f999ee2d873a1be46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":1751.5},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"772e3ad2c6e74b1b8792e4ac6ca03050",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":504,
              "y":1740},
            "size":{
              "width":192,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a24e57304e14fe3a0a40906e2c620d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":504,
                  "y":1740},
                "size":{
                  "width":192,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d860a0fd27da43a6b41568a5c188a436",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":448,
              "y":1740},
            "size":{
              "width":46,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3afa076e216c437eabfcdb9df7c5b397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":448,
                  "y":1740},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e681056208704765823013531ef46a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":463,
              "y":1798},
            "size":{
              "width":73,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fadb1c81f2b64aa989a4cb872d45c09a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":463,
                  "y":1798},
                "size":{
                  "width":73,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5238c9302a748a183870cb9af8ba324",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":546,
              "y":1798},
            "size":{
              "width":323,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dce2d9553037426fbbd8859007f4cca4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":546,
                  "y":1798},
                "size":{
                  "width":323,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edfe4fd74a9b436885c363c539756ac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":930,
              "y":1760},
            "size":{
              "width":270,
              "height":132}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b514f713ace14622bcb1e00f7918ace2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":930,
                  "y":1760},
                "size":{
                  "width":270,
                  "height":132}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-05_官方活动分享页面/u112.png"}},
{
          "id":"3becee1227634756817ea61465adc44e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":10,
              "y":1130},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b378c2dc90d4ab8aa514a74880b0705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":10,
                  "y":1130},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e0dfe4c23ee4fd88e65174a1a452bc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":934,
              "y":1718},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceb94ac4bb1e4aa697eb44a056706adf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":934,
                  "y":1718},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5057ba9c9d442d7a6106a4212abbc00",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":936,
              "y":1775},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f978d37dc374771b3144a32b2e70113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":936,
                  "y":1775},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"076fb27d20b9436fb75eabf6fa5f494d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":934,
              "y":1796},
            "size":{
              "width":246,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/03-05_官方活动分享页面/u120_line.png"}},
{
          "id":"886b32d6b5a447feab25b77c02dbacc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":955,
              "y":1796},
            "size":{
              "width":204,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2f6e58b2dec4ddab5289aa8d92b4430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":955,
                  "y":1796},
                "size":{
                  "width":204,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"409707160b8547a49c25c32bd8dc6585",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":948,
              "y":1857},
            "size":{
              "width":95,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fdaaeb9bbde34ec9a856e477b8bb1e1c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":1064,
              "y":1857},
            "size":{
              "width":106,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"611b41cc1239468eaa6b17a7f3065e8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":426,
              "y":101},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41129697b41a445c92ca0bcf60923de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":426,
                  "y":101},
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u10.png"}},
{
          "id":"b891cca80492405e91fa373806830495",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":116},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/01_-_金币任务/u14_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/01_-_金币任务/u14_line.png"}},
{
          "id":"57a37153e4cd47dfae44d7e0d8a1c6ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":463,
              "y":113},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f496b24150f4457f93170b2829938ef2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":463,
                  "y":113},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5145d764ca9248ae9baa7cce98bc80f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":113},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70c8a13c405344008d48f3dd1efac7fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":742,
                  "y":113},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "4e436cfc9c4c495985b56bfc5dce0d62":{
      "packageId":"4e436cfc9c4c495985b56bfc5dce0d62",
      "type":"Axure:Master",
      "name":"手机页面",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd34f4f4069a42f583ba384d38e35c69",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":0,
                "y":1},
              "size":{
                "width":360,
                "height":620}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fc8e86c42192410d80c957b0e09679ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":1},
                  "size":{
                    "width":360,
                    "height":620}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/02-_签到/u1.png",
              "normal~":"images/02-_签到/u1.png"}}]}}},
  "objectPaths":{
    "433c9ae6bdb1476483f2fb8bfcc0b78c":{
      "scriptId":"u0",
      "fd34f4f4069a42f583ba384d38e35c69":{
        "scriptId":"u1"},
      "fc8e86c42192410d80c957b0e09679ed":{
        "scriptId":"u2"}},
    "7032af316b1d4984b72b1ba3d106920a":{
      "scriptId":"u3"},
    "6b273a89987c496087b32434c5b1407a":{
      "scriptId":"u4"},
    "468e0163b2514f71a169c59e9d3a5bcb":{
      "scriptId":"u5"},
    "0a4d79f84b454265a4bf3a533f45a020":{
      "scriptId":"u6"},
    "f38b5b08fed44b469efb70ee5b71140a":{
      "scriptId":"u7"},
    "55a111c3cd8c41dfb89ebcc09b8d33d3":{
      "scriptId":"u8"},
    "890641c13d944614ac52f48e5607677f":{
      "scriptId":"u9"},
    "2b85adee03c04704a062281bc410be6b":{
      "scriptId":"u10"},
    "4c7c3af336b34c3fa84292fea8b64a4a":{
      "scriptId":"u11"},
    "158540089879478592237fb0c0750687":{
      "scriptId":"u12"},
    "cef962d2603c4c0c9c1483c3acbc2e86":{
      "scriptId":"u13"},
    "d18ccfd6586f4fcead73fd50366e810e":{
      "scriptId":"u14"},
    "9ecf73569ce74bb58d4717ed5332bda6":{
      "scriptId":"u15"},
    "66a730bba4034e588d6775d2ad00b3d9":{
      "scriptId":"u16"},
    "2644675cd0134726ad7b26286b61fa08":{
      "scriptId":"u17"},
    "9089f2cf58a74da49a1a7d9a286c5603":{
      "scriptId":"u18"},
    "183a644fbc53488082e5cb51ce77b805":{
      "scriptId":"u19"},
    "97140e19064e4c0484a96676654a0b48":{
      "scriptId":"u20"},
    "2559e38cdba14f75ad962779e1f16cec":{
      "scriptId":"u21"},
    "436548b5b9a0462a9733460b5e74b4bc":{
      "scriptId":"u22"},
    "cbca6bcff2394d8aa1777530c2e3cb9b":{
      "scriptId":"u23"},
    "38367a349c95437aa8e27fc5bdc3a4be":{
      "scriptId":"u24"},
    "6fd4afd7a7384816bb07b71f718a0805":{
      "scriptId":"u25"},
    "1749918d724c4bedacd4c8155d10ab0e":{
      "scriptId":"u26"},
    "a4c787f1cb1548d6801431bf1a1a3385":{
      "scriptId":"u27"},
    "d792747dca32462da18b8cbe0e79b3af":{
      "scriptId":"u28"},
    "4b3f710b577a4d67ad069e81d311295a":{
      "scriptId":"u29"},
    "c96174c2442346cd88ff19d23e9962e5":{
      "scriptId":"u30"},
    "bd1a7fd48160435d94a9dc9e44a08fbb":{
      "scriptId":"u31"},
    "e0159710c3b441cf9be34bce5af2202a":{
      "scriptId":"u32"},
    "295cb76f5a4649ce8ec00a4a947a22c1":{
      "scriptId":"u33"},
    "3f5057bb0d8449b38d799d15ba26ebbb":{
      "scriptId":"u34"},
    "79c5968e9bc94cfeb9e4833f8e1f1904":{
      "scriptId":"u35"},
    "24102c950a024ee2b2623afb17da9aee":{
      "scriptId":"u36"},
    "8c19a2bab2454f9a8cb7d2f964de3bab":{
      "scriptId":"u37"},
    "ac8945bd664a44f0a153f60e26861e20":{
      "scriptId":"u38"},
    "188c97b511a143668c078b843d04506d":{
      "scriptId":"u39"},
    "8c59829cf40c43c1a5ee0b4575aacd47":{
      "scriptId":"u40"},
    "1151ae9790a3453a90aeeaef47db026c":{
      "scriptId":"u41"},
    "72b5aca8e92944168d161888cce691f7":{
      "scriptId":"u42"},
    "18a479777e194392b69564860863d094":{
      "scriptId":"u43"},
    "3163df44b7784448b0dfb8c873d3dd6c":{
      "scriptId":"u44"},
    "352a88a95f09467c8d3ab510fae3702c":{
      "scriptId":"u45"},
    "c9f059a2843d4bb69cecdadd1cf3328d":{
      "scriptId":"u46"},
    "4b106b3ecd1b43f4981141034afb3aa0":{
      "scriptId":"u47"},
    "a5c37806f2ae47c8b5e94986d38f32eb":{
      "scriptId":"u48"},
    "2bf1e0fb56d84aef9b31d5e7ac784c0d":{
      "scriptId":"u49"},
    "792de5e226664c85a88349112dd89260":{
      "scriptId":"u50"},
    "e179bb00cc7b47db970b8666c0f68a19":{
      "scriptId":"u51"},
    "01181fe959924aad8bbe04bcb52dd6ac":{
      "scriptId":"u52"},
    "f77ae5d0e7794ada92151af96338b944":{
      "scriptId":"u53"},
    "309cd05fb6614600af6626a0dfbf1def":{
      "scriptId":"u54"},
    "2156d6aa2b434cfc83dc05291b505f56":{
      "scriptId":"u55"},
    "88772de1a2e84c1d8acda4ed4a4ba00e":{
      "scriptId":"u56"},
    "f8ec4ea9f27e413f9b15cbd0eab35e3a":{
      "scriptId":"u57"},
    "32ac9548a6344905bf9c9433cc307136":{
      "scriptId":"u58"},
    "7f162c6924364b9bb2520a59287c6f1e":{
      "scriptId":"u59"},
    "104555be94e749eab9763d8487fa6df3":{
      "scriptId":"u60"},
    "98ef28a013f34488bbcfc552ddaad5d3":{
      "scriptId":"u61"},
    "27435028e0a545c3a993336efcf73c75":{
      "scriptId":"u62"},
    "25e544b13e1c4082b20384dbcf952a0a":{
      "scriptId":"u63"},
    "64d41ee861784d688f85cd3b586aca87":{
      "scriptId":"u64"},
    "c36828e39d4546ce9ff3dc08510dbfe9":{
      "scriptId":"u65"},
    "7b5665617cb04225a614006307e52169":{
      "scriptId":"u66"},
    "6a200fa7590047a1ad4552acbe4bb475":{
      "scriptId":"u67"},
    "bee4a14dfc4c4511bf88793f05052b50":{
      "scriptId":"u68"},
    "5cb913e6a2374526bcbe8cae6a467edb":{
      "scriptId":"u69",
      "fd34f4f4069a42f583ba384d38e35c69":{
        "scriptId":"u70"},
      "fc8e86c42192410d80c957b0e09679ed":{
        "scriptId":"u71"}},
    "0a40b090891f415aae6c48765cf614e7":{
      "scriptId":"u72"},
    "2ce09003c477403f96c3bd0f1994a54d":{
      "scriptId":"u73"},
    "38f69ba9b3ec4ac39c75174d96514c3a":{
      "scriptId":"u74"},
    "5c72cdc51de941cca9da88fe0aa6673b":{
      "scriptId":"u75"},
    "d93eb6054b2944f3a80992975a18c043":{
      "scriptId":"u76"},
    "b0464339474a4b08b405e5e3f38da7d5":{
      "scriptId":"u77"},
    "3b9fea648cad4a80811f5c18001c84ad":{
      "scriptId":"u78"},
    "afe28307c68a43bfb73f67aca0500454":{
      "scriptId":"u79"},
    "2ff2e398dc8c4e2799109b0575f3545b":{
      "scriptId":"u80"},
    "2b35cef5f0834ba8bb8d4b197b77f156":{
      "scriptId":"u81"},
    "988d44c99b1d42fcb6778816596ff7e2":{
      "scriptId":"u82"},
    "474421a6570d4a5ea5f7de3e17e5e110":{
      "scriptId":"u83"},
    "d9e7e461aedb483d99e1c7db4389ad12":{
      "scriptId":"u84"},
    "ad3f6509b1984972889e8fac54e6c1aa":{
      "scriptId":"u85"},
    "3f6854a4984849c78ab24b9ae12c6d8e":{
      "scriptId":"u86"},
    "ef12d1f7fe3d415ea740dba9a5aed999":{
      "scriptId":"u87"},
    "cfe09d6de32244289a6072f1b531d165":{
      "scriptId":"u88"},
    "7932505879c34a2fbee9b15d7e620227":{
      "scriptId":"u89"},
    "26e5f73b126d43a78ff97a2c7137ced8":{
      "scriptId":"u90"},
    "5f0b9fd2a6f24840b67e1d77a6ba2637":{
      "scriptId":"u91"},
    "965a68c25e6b402b8a88e6559dc91a3a":{
      "scriptId":"u92"},
    "969e57dfe5944090b97ba1dd89a00374":{
      "scriptId":"u93"},
    "61cb2b9955d241ca9296c25e4d581a56":{
      "scriptId":"u94"},
    "6e2301363d0b455b98731bcdedf04ffd":{
      "scriptId":"u95"},
    "2dea9b0dccf44d5c89d717c34189f11c":{
      "scriptId":"u96"},
    "bb5528f0ecbf4ec2a6c052b8c2ffce81":{
      "scriptId":"u97"},
    "1a3db5dd41ac456fb115f3c6c2ec9562":{
      "scriptId":"u98"},
    "f62f2075952645bc87e9ff40d54f4b84":{
      "scriptId":"u99"},
    "f61e5d637cdf49caa507541071c97b0a":{
      "scriptId":"u100"},
    "c841e16a9f8041dd91fefc8eddc4e921":{
      "scriptId":"u101"},
    "2c38278e33f14ef9add42dcf5af80920":{
      "scriptId":"u102"},
    "43ce57e3f078483f999ee2d873a1be46":{
      "scriptId":"u103"},
    "772e3ad2c6e74b1b8792e4ac6ca03050":{
      "scriptId":"u104"},
    "3a24e57304e14fe3a0a40906e2c620d4":{
      "scriptId":"u105"},
    "d860a0fd27da43a6b41568a5c188a436":{
      "scriptId":"u106"},
    "3afa076e216c437eabfcdb9df7c5b397":{
      "scriptId":"u107"},
    "e681056208704765823013531ef46a63":{
      "scriptId":"u108"},
    "fadb1c81f2b64aa989a4cb872d45c09a":{
      "scriptId":"u109"},
    "c5238c9302a748a183870cb9af8ba324":{
      "scriptId":"u110"},
    "dce2d9553037426fbbd8859007f4cca4":{
      "scriptId":"u111"},
    "edfe4fd74a9b436885c363c539756ac2":{
      "scriptId":"u112"},
    "b514f713ace14622bcb1e00f7918ace2":{
      "scriptId":"u113"},
    "3becee1227634756817ea61465adc44e":{
      "scriptId":"u114"},
    "5b378c2dc90d4ab8aa514a74880b0705":{
      "scriptId":"u115"},
    "0e0dfe4c23ee4fd88e65174a1a452bc9":{
      "scriptId":"u116"},
    "ceb94ac4bb1e4aa697eb44a056706adf":{
      "scriptId":"u117"},
    "f5057ba9c9d442d7a6106a4212abbc00":{
      "scriptId":"u118"},
    "2f978d37dc374771b3144a32b2e70113":{
      "scriptId":"u119"},
    "076fb27d20b9436fb75eabf6fa5f494d":{
      "scriptId":"u120"},
    "886b32d6b5a447feab25b77c02dbacc0":{
      "scriptId":"u121"},
    "c2f6e58b2dec4ddab5289aa8d92b4430":{
      "scriptId":"u122"},
    "409707160b8547a49c25c32bd8dc6585":{
      "scriptId":"u123"},
    "fdaaeb9bbde34ec9a856e477b8bb1e1c":{
      "scriptId":"u124"},
    "611b41cc1239468eaa6b17a7f3065e8b":{
      "scriptId":"u125"},
    "41129697b41a445c92ca0bcf60923de9":{
      "scriptId":"u126"},
    "b891cca80492405e91fa373806830495":{
      "scriptId":"u127"},
    "57a37153e4cd47dfae44d7e0d8a1c6ce":{
      "scriptId":"u128"},
    "f496b24150f4457f93170b2829938ef2":{
      "scriptId":"u129"},
    "5145d764ca9248ae9baa7cce98bc80f4":{
      "scriptId":"u130"},
    "70c8a13c405344008d48f3dd1efac7fd":{
      "scriptId":"u131"}}});