$axure.loadCurrentPage({
  "url":"02-_签到.html",
  "generationDate":new Date(1460019145043.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4aa559450fd2460e82b38683b2cfc4c3",
    "type":"Axure:Page",
    "name":"02- 签到",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e3006584b7e4a0388e9c8b2f844e6e3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":30}},
          "adaptiveStyles":{
},
          "masterId":"4e436cfc9c4c495985b56bfc5dce0d62"},
{
          "id":"c9e3f0588ee84d2fa3d61a718bc3c60d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":30,
              "y":30},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"164bc394389a44ad9868385fd2f03d01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":30,
                  "y":30},
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u10.png"}},
{
          "id":"85f48d80cb2d4686858381b4d72e57d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":42},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c203ea40aa14997b2ada2df7337f1dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":42},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bab0ace1438496cbeccf0fe3b668fe6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":45},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/01_-_金币任务/u14_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/01_-_金币任务/u14_line.png"}},
{
          "id":"f80212aa90304cd290df3b6da8f4adef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":30,
              "y":72},
            "size":{
              "width":360,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af56119e214f4a39b332465dbcd93b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":30,
                  "y":72},
                "size":{
                  "width":360,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-_签到/u8.png"}},
{
          "id":"2f56c3beb3644afa80db31aa954df088",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":30,
              "y":135},
            "size":{
              "width":360,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79584f203fe94cb79df32d26ddd34f96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":30,
                  "y":135},
                "size":{
                  "width":360,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-_签到/u10.png"}},
{
          "id":"2ba8697ccd924bfcb1a292475659bb88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":151},
            "size":{
              "width":76,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f44c41d647f43c798ab3a7c9555047b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":151},
                "size":{
                  "width":76,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ed7f2dfdaf74fe2a5dbca0ac25f0f83",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":304,
              "y":144},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ce05c9033bd548a0acd4e39849dd4c97",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":179},
            "size":{
              "width":350,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/02-_签到/u15_line.png"}},
{
          "id":"8f529835d175401094e9c2bccdf14dfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":30,
              "y":322},
            "size":{
              "width":360,
              "height":298}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33263041aed14ca58725f2825e29c46b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":30,
                  "y":322},
                "size":{
                  "width":360,
                  "height":298}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-_签到/u16.png"}},
{
          "id":"11bfaa3c0751407ca9da32a0eaa62300",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6633,
              "opacity":1},
            "location":{
              "x":165,
              "y":339},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4935d82fa414dc5b62aa77967fbfa58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633,
                  "opacity":1},
                "location":{
                  "x":165,
                  "y":339},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e6e9da628fe498db15386bfa95f2035",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":369},
            "size":{
              "width":99,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/02-_签到/u20_line.png"}},
{
          "id":"24f0e1e0bb6f45629657ad062497b454",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":68,
              "y":397},
            "size":{
              "width":65,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91bb7b58ee7a47f38c0860e9039c755e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":68,
                  "y":397},
                "size":{
                  "width":65,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-_签到/u21.png"}},
{
          "id":"6073fff6b35a43bcbb9c25b2ff68aa3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":100,
              "y":390},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fef1761d420144fd81572cf5aceaeba1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":390},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d00a68d6276a45d7af13d2e42e510965",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":78,
              "y":464},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00e92214ee4546f39c41e6005de727fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":78,
                  "y":464},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"036cd5bc969747f59bf0279871547867",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":175,
              "y":397},
            "size":{
              "width":65,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d2c0728937642f8926ea6468c806084",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":175,
                  "y":397},
                "size":{
                  "width":65,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-_签到/u21.png"}},
{
          "id":"e408404237d34b379c9be40178339f94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":207,
              "y":390},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e915d855f7f04d1292de29509f2905cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":207,
                  "y":390},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd4cdc9ca56042aa98ce9b04f49bebaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":175,
              "y":463},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcfee11668794fbdb14122e811171d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":175,
                  "y":463},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cca016a217f47dc96c50400948be898",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":285,
              "y":397},
            "size":{
              "width":65,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e950fd95e7564f88aae64413ce908588",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":285,
                  "y":397},
                "size":{
                  "width":65,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-_签到/u21.png"}},
{
          "id":"d51e954bc3064c21b993c89f0d9ece9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":284,
              "y":465},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70ce8a8f613b4237ab5b6f72ac02e745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":284,
                  "y":465},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c1406adc3d4283ad36ca7a9c1ea63c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":65,
              "y":503},
            "size":{
              "width":65,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ecceaeb1fc94e8b8ef6f018e57e7e74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":65,
                  "y":503},
                "size":{
                  "width":65,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-_签到/u21.png"}},
{
          "id":"09b8de8912b748c2af6da1816b39a371",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":65,
              "y":573},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0f973e58ef742c9ad9db22310888cd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":65,
                  "y":573},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b034095f39bb41c19872aa1e070c4b19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":170,
              "y":501},
            "size":{
              "width":65,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d67ed54675c4a628c9956157ea1e5e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":170,
                  "y":501},
                "size":{
                  "width":65,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-_签到/u21.png"}},
{
          "id":"b90a617390534ce8987140a4cc163631",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":167,
              "y":572},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bff2a2333c4463badd863882792a032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":167,
                  "y":572},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19a93bb2c8af439bbe66e0c68574773d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":282,
              "y":503},
            "size":{
              "width":65,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e491b9699794a8a9a37ffc01b4956eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":282,
                  "y":503},
                "size":{
                  "width":65,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-_签到/u21.png"}},
{
          "id":"2870dd3e7c034d928733b8fc7f4ca424",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":280,
              "y":573},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10be3d93eceb42a38db4db02afe330ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":280,
                  "y":573},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"091090d6fda549d39bf78783b53d3c10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":30,
              "y":632},
            "size":{
              "width":360,
              "height":218}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de83d4bd30a340119ec8e218a0332e13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":30,
                  "y":632},
                "size":{
                  "width":360,
                  "height":218}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/02-_签到/u49.png"}},
{
          "id":"c8fa2d0090fa4791afbc5325e4b42f13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":172,
              "y":650},
            "size":{
              "width":76,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56d40bc02bf342d8a111b5066c2dc858",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":172,
                  "y":650},
                "size":{
                  "width":76,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"617a28553e274a58a6b17766458c8b38",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":675},
            "size":{
              "width":350,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/02-_签到/u15_line.png"}},
{
          "id":"3e971412b6234a22aac2f8bdc56f1eb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":52,
              "y":691},
            "size":{
              "width":320,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72498b4418bd47988f78071db73d371b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":52,
                  "y":691},
                "size":{
                  "width":320,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d324ef9f7a6044f39d3050d71c08dcdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "location":{
              "x":478,
              "y":146},
            "size":{
              "width":318,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29dcf8773760469c8709c5e1d4603020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "location":{
                  "x":478,
                  "y":146},
                "size":{
                  "width":318,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fde35a00c1c4c778f0929ea3aefe38b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":156},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"700949abb5024be59c3dcc7d7745ad4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":156},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"454d5ddd2e0a48e287f7735159fc6fbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "location":{
              "x":478,
              "y":205},
            "size":{
              "width":402,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e78ae02074d4889923191477ac9dee2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "location":{
                  "x":478,
                  "y":205},
                "size":{
                  "width":402,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d80d533c98a14e348a1ad905fc8145db",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":215},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc44a5af37fe472bb6142d752e9473b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":215},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"d2b12700806747b688ede02b9470c27e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "location":{
              "x":478,
              "y":520},
            "size":{
              "width":462,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fc83ecc3e1841d9b7fe18403b85acad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "location":{
                  "x":478,
                  "y":520},
                "size":{
                  "width":462,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16123d43f72541eda3e29765cbe88077",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":535.5},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dd5f2a435574f69be9be306bf56a35b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":535.5},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"3519bc2f6953459ebe51412037c5286f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":478,
              "y":553},
            "size":{
              "width":762,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2cbeae6d2d442f58e5123ab0a4b5a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":478,
                  "y":553},
                "size":{
                  "width":762,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e5c668b27e14aa3bbddd219cf175ad7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "location":{
              "x":486,
              "y":663},
            "size":{
              "width":94,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1a5d49552264a809789c5c07b4c1fd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "location":{
                  "x":486,
                  "y":663},
                "size":{
                  "width":94,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d13413d04f054f8a8fc2aa5325a22708",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":416,
              "y":673},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"314a3bad50af4597b5030acfc7cb4243",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":416,
                  "y":673},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"49ff820c0ca14a63956a00f0b343bcef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":486,
              "y":783},
            "size":{
              "width":360,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed8dd0de6b7b478dac55d9f222bf1cca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":486,
                  "y":783},
                "size":{
                  "width":360,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u43.png"}},
{
          "id":"fdc64a48876f468d8ccb16c0130cd2c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":807},
            "size":{
              "width":32,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ebc606c3096432883fc7a6d91cb3540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":807},
                "size":{
                  "width":32,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u23.png"}},
{
          "id":"e2d8d68c212f4b39a90af1ffd7732107",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":545,
              "y":813},
            "size":{
              "width":145,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ef1eba058b24ebd948604fcc8f72938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":545,
                  "y":813},
                "size":{
                  "width":145,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"727251fa32984f6fa836dc32d4e5c509",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":486,
              "y":695},
            "size":{
              "width":384,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f00e076e23941b0b869b1037501894f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":486,
                  "y":695},
                "size":{
                  "width":384,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"715ec4e3c23c470896872be043b03610",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":486,
              "y":728},
            "size":{
              "width":504,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbd71c02e9ef4802817b8c6149b64128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":486,
                  "y":728},
                "size":{
                  "width":504,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ea64aa45df24f5c911ef829f2df9ba6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":486,
              "y":893},
            "size":{
              "width":360,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ad76d8141fc4368baa7bc4caee2459f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":486,
                  "y":893},
                "size":{
                  "width":360,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u43.png"}},
{
          "id":"2ce6b2997a0d453da229299f3568c4e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":917},
            "size":{
              "width":32,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d4eccaffd7d490994dbe1b7df316f01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":917},
                "size":{
                  "width":32,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u23.png"}},
{
          "id":"7b07e0c37c0f47b6b61b37091a93d29e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":545,
              "y":923},
            "size":{
              "width":165,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb8f9ad3aa484035a6f0d089137286bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":545,
                  "y":923},
                "size":{
                  "width":165,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4f2c32499394a6f9f3236a5c4ae61ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":487,
              "y":999},
            "size":{
              "width":360,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f82f42250244b11a1bc7946fc27466c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":487,
                  "y":999},
                "size":{
                  "width":360,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u43.png"}},
{
          "id":"4b024039437e46858c2936351c29c180",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":1023},
            "size":{
              "width":32,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccb67c1b154d4b26aa21f52b9c3095fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":1023},
                "size":{
                  "width":32,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u23.png"}},
{
          "id":"066d42038e514c9fb21a59631deef5c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":546,
              "y":1029},
            "size":{
              "width":245,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d12886c543b4491b2b71a448e0f82e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":546,
                  "y":1029},
                "size":{
                  "width":245,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4b1348c244a4d5ea234e5e9aaaac64c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "location":{
              "x":478,
              "y":88},
            "size":{
              "width":62,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bce49a4017742b3a305797ea51f209d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "location":{
                  "x":478,
                  "y":88},
                "size":{
                  "width":62,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65e71289244842bab0f8b3c9cd935cf5",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":98.5},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4b4bcc5211d4613a446d424ee0b00ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":98.5},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"26200109f7d741c6a839e9d6725a0b08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":148,
              "y":365},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ae24ecad20a462db972da7c0dd8ed18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":148,
                  "y":365},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1aa8155d80a47d98356a44b3be3218f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":367},
            "size":{
              "width":115,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/02-_签到/u102_line.png"}}]}},
  "masters":{
    "4e436cfc9c4c495985b56bfc5dce0d62":{
      "packageId":"4e436cfc9c4c495985b56bfc5dce0d62",
      "type":"Axure:Master",
      "name":"手机页面",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd34f4f4069a42f583ba384d38e35c69",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":0,
                "y":1},
              "size":{
                "width":360,
                "height":620}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fc8e86c42192410d80c957b0e09679ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":1},
                  "size":{
                    "width":360,
                    "height":620}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/02-_签到/u1.png"}}]}}},
  "objectPaths":{
    "1e3006584b7e4a0388e9c8b2f844e6e3":{
      "scriptId":"u0",
      "fd34f4f4069a42f583ba384d38e35c69":{
        "scriptId":"u1"},
      "fc8e86c42192410d80c957b0e09679ed":{
        "scriptId":"u2"}},
    "c9e3f0588ee84d2fa3d61a718bc3c60d":{
      "scriptId":"u3"},
    "164bc394389a44ad9868385fd2f03d01":{
      "scriptId":"u4"},
    "85f48d80cb2d4686858381b4d72e57d1":{
      "scriptId":"u5"},
    "6c203ea40aa14997b2ada2df7337f1dd":{
      "scriptId":"u6"},
    "5bab0ace1438496cbeccf0fe3b668fe6":{
      "scriptId":"u7"},
    "f80212aa90304cd290df3b6da8f4adef":{
      "scriptId":"u8"},
    "af56119e214f4a39b332465dbcd93b71":{
      "scriptId":"u9"},
    "2f56c3beb3644afa80db31aa954df088":{
      "scriptId":"u10"},
    "79584f203fe94cb79df32d26ddd34f96":{
      "scriptId":"u11"},
    "2ba8697ccd924bfcb1a292475659bb88":{
      "scriptId":"u12"},
    "1f44c41d647f43c798ab3a7c9555047b":{
      "scriptId":"u13"},
    "6ed7f2dfdaf74fe2a5dbca0ac25f0f83":{
      "scriptId":"u14"},
    "ce05c9033bd548a0acd4e39849dd4c97":{
      "scriptId":"u15"},
    "8f529835d175401094e9c2bccdf14dfc":{
      "scriptId":"u16"},
    "33263041aed14ca58725f2825e29c46b":{
      "scriptId":"u17"},
    "11bfaa3c0751407ca9da32a0eaa62300":{
      "scriptId":"u18"},
    "d4935d82fa414dc5b62aa77967fbfa58":{
      "scriptId":"u19"},
    "0e6e9da628fe498db15386bfa95f2035":{
      "scriptId":"u20"},
    "24f0e1e0bb6f45629657ad062497b454":{
      "scriptId":"u21"},
    "91bb7b58ee7a47f38c0860e9039c755e":{
      "scriptId":"u22"},
    "6073fff6b35a43bcbb9c25b2ff68aa3e":{
      "scriptId":"u23"},
    "fef1761d420144fd81572cf5aceaeba1":{
      "scriptId":"u24"},
    "d00a68d6276a45d7af13d2e42e510965":{
      "scriptId":"u25"},
    "00e92214ee4546f39c41e6005de727fe":{
      "scriptId":"u26"},
    "036cd5bc969747f59bf0279871547867":{
      "scriptId":"u27"},
    "1d2c0728937642f8926ea6468c806084":{
      "scriptId":"u28"},
    "e408404237d34b379c9be40178339f94":{
      "scriptId":"u29"},
    "e915d855f7f04d1292de29509f2905cd":{
      "scriptId":"u30"},
    "bd4cdc9ca56042aa98ce9b04f49bebaf":{
      "scriptId":"u31"},
    "dcfee11668794fbdb14122e811171d03":{
      "scriptId":"u32"},
    "2cca016a217f47dc96c50400948be898":{
      "scriptId":"u33"},
    "e950fd95e7564f88aae64413ce908588":{
      "scriptId":"u34"},
    "d51e954bc3064c21b993c89f0d9ece9e":{
      "scriptId":"u35"},
    "70ce8a8f613b4237ab5b6f72ac02e745":{
      "scriptId":"u36"},
    "f0c1406adc3d4283ad36ca7a9c1ea63c":{
      "scriptId":"u37"},
    "5ecceaeb1fc94e8b8ef6f018e57e7e74":{
      "scriptId":"u38"},
    "09b8de8912b748c2af6da1816b39a371":{
      "scriptId":"u39"},
    "b0f973e58ef742c9ad9db22310888cd6":{
      "scriptId":"u40"},
    "b034095f39bb41c19872aa1e070c4b19":{
      "scriptId":"u41"},
    "2d67ed54675c4a628c9956157ea1e5e1":{
      "scriptId":"u42"},
    "b90a617390534ce8987140a4cc163631":{
      "scriptId":"u43"},
    "3bff2a2333c4463badd863882792a032":{
      "scriptId":"u44"},
    "19a93bb2c8af439bbe66e0c68574773d":{
      "scriptId":"u45"},
    "8e491b9699794a8a9a37ffc01b4956eb":{
      "scriptId":"u46"},
    "2870dd3e7c034d928733b8fc7f4ca424":{
      "scriptId":"u47"},
    "10be3d93eceb42a38db4db02afe330ed":{
      "scriptId":"u48"},
    "091090d6fda549d39bf78783b53d3c10":{
      "scriptId":"u49"},
    "de83d4bd30a340119ec8e218a0332e13":{
      "scriptId":"u50"},
    "c8fa2d0090fa4791afbc5325e4b42f13":{
      "scriptId":"u51"},
    "56d40bc02bf342d8a111b5066c2dc858":{
      "scriptId":"u52"},
    "617a28553e274a58a6b17766458c8b38":{
      "scriptId":"u53"},
    "3e971412b6234a22aac2f8bdc56f1eb3":{
      "scriptId":"u54"},
    "72498b4418bd47988f78071db73d371b":{
      "scriptId":"u55"},
    "d324ef9f7a6044f39d3050d71c08dcdb":{
      "scriptId":"u56"},
    "29dcf8773760469c8709c5e1d4603020":{
      "scriptId":"u57"},
    "2fde35a00c1c4c778f0929ea3aefe38b":{
      "scriptId":"u58"},
    "700949abb5024be59c3dcc7d7745ad4a":{
      "scriptId":"u59"},
    "454d5ddd2e0a48e287f7735159fc6fbd":{
      "scriptId":"u60"},
    "9e78ae02074d4889923191477ac9dee2":{
      "scriptId":"u61"},
    "d80d533c98a14e348a1ad905fc8145db":{
      "scriptId":"u62"},
    "dc44a5af37fe472bb6142d752e9473b3":{
      "scriptId":"u63"},
    "d2b12700806747b688ede02b9470c27e":{
      "scriptId":"u64"},
    "9fc83ecc3e1841d9b7fe18403b85acad":{
      "scriptId":"u65"},
    "16123d43f72541eda3e29765cbe88077":{
      "scriptId":"u66"},
    "6dd5f2a435574f69be9be306bf56a35b":{
      "scriptId":"u67"},
    "3519bc2f6953459ebe51412037c5286f":{
      "scriptId":"u68"},
    "b2cbeae6d2d442f58e5123ab0a4b5a42":{
      "scriptId":"u69"},
    "3e5c668b27e14aa3bbddd219cf175ad7":{
      "scriptId":"u70"},
    "b1a5d49552264a809789c5c07b4c1fd3":{
      "scriptId":"u71"},
    "d13413d04f054f8a8fc2aa5325a22708":{
      "scriptId":"u72"},
    "314a3bad50af4597b5030acfc7cb4243":{
      "scriptId":"u73"},
    "49ff820c0ca14a63956a00f0b343bcef":{
      "scriptId":"u74"},
    "ed8dd0de6b7b478dac55d9f222bf1cca":{
      "scriptId":"u75"},
    "fdc64a48876f468d8ccb16c0130cd2c1":{
      "scriptId":"u76"},
    "2ebc606c3096432883fc7a6d91cb3540":{
      "scriptId":"u77"},
    "e2d8d68c212f4b39a90af1ffd7732107":{
      "scriptId":"u78"},
    "0ef1eba058b24ebd948604fcc8f72938":{
      "scriptId":"u79"},
    "727251fa32984f6fa836dc32d4e5c509":{
      "scriptId":"u80"},
    "1f00e076e23941b0b869b1037501894f":{
      "scriptId":"u81"},
    "715ec4e3c23c470896872be043b03610":{
      "scriptId":"u82"},
    "bbd71c02e9ef4802817b8c6149b64128":{
      "scriptId":"u83"},
    "7ea64aa45df24f5c911ef829f2df9ba6":{
      "scriptId":"u84"},
    "8ad76d8141fc4368baa7bc4caee2459f":{
      "scriptId":"u85"},
    "2ce6b2997a0d453da229299f3568c4e9":{
      "scriptId":"u86"},
    "2d4eccaffd7d490994dbe1b7df316f01":{
      "scriptId":"u87"},
    "7b07e0c37c0f47b6b61b37091a93d29e":{
      "scriptId":"u88"},
    "eb8f9ad3aa484035a6f0d089137286bd":{
      "scriptId":"u89"},
    "e4f2c32499394a6f9f3236a5c4ae61ee":{
      "scriptId":"u90"},
    "2f82f42250244b11a1bc7946fc27466c":{
      "scriptId":"u91"},
    "4b024039437e46858c2936351c29c180":{
      "scriptId":"u92"},
    "ccb67c1b154d4b26aa21f52b9c3095fa":{
      "scriptId":"u93"},
    "066d42038e514c9fb21a59631deef5c8":{
      "scriptId":"u94"},
    "2d12886c543b4491b2b71a448e0f82e8":{
      "scriptId":"u95"},
    "c4b1348c244a4d5ea234e5e9aaaac64c":{
      "scriptId":"u96"},
    "5bce49a4017742b3a305797ea51f209d":{
      "scriptId":"u97"},
    "65e71289244842bab0f8b3c9cd935cf5":{
      "scriptId":"u98"},
    "c4b4bcc5211d4613a446d424ee0b00ad":{
      "scriptId":"u99"},
    "26200109f7d741c6a839e9d6725a0b08":{
      "scriptId":"u100"},
    "4ae24ecad20a462db972da7c0dd8ed18":{
      "scriptId":"u101"},
    "a1aa8155d80a47d98356a44b3be3218f":{
      "scriptId":"u102"}}});