$axure.loadCurrentPage({
  "url":"03-06_游戏活动快讯分享页面.html",
  "generationDate":new Date(1460019147456.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"95b8b97903034397acb80c0f5bdae9e0",
    "type":"Axure:Page",
    "name":"03-06 游戏活动快讯分享页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8e77826aff334830a085744f5cec193a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":28,
              "y":101},
            "size":{
              "width":263,
              "height":135}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14519abc80044504b4462caf129ed963",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":28,
                  "y":101},
                "size":{
                  "width":263,
                  "height":135}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-05_官方活动分享页面/u20.png"}},
{
          "id":"6ad7c3cc427b4b6285ebc8cf2e0a069d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":41,
              "y":114},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2b8fb0fe63741fda77130b16913d468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":41,
                  "y":114},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68c9906d652949718d74d6f042873ba3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":123,
              "y":158},
            "size":{
              "width":82,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85516b7c178d42a6a427f7a77ba94aec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":123,
                  "y":158},
                "size":{
                  "width":82,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"455c2bb00df1447c942844465fad8d50",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":36,
              "y":246},
            "size":{
              "width":47,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7615a15fc49745ee8531c98e98342574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":36,
                  "y":246},
                "size":{
                  "width":47,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2ef94b0d602408795e5b8b1c6f4a60e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":28,
              "y":60},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47bcefa4a8d444e9ad40c2fe9dd5683e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":28,
                  "y":60},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8035931d1b5f41968dbb528d6913900d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":148},
            "size":{
              "width":51,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af0e62bec45c43158a211839b62d781b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":148},
                "size":{
                  "width":51,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-06_游戏活动快讯分享页面/u10.png"}},
{
          "id":"913355b1b7e744f493853422a98e279c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":101}},
          "adaptiveStyles":{
},
          "masterId":"14f7fa0e12e34a0f8729b3e0c967e282"},
{
          "id":"eaae753b5b954440bf3bc4b0a74eb713",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":370,
              "y":101},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"209da9a4aa0a469b874815261ce8c9b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":370,
                  "y":101},
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/01_-_金币任务/u10.png"}},
{
          "id":"b32bda89f5d047508efea20e38c584f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":113},
            "size":{
              "width":82,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0ee1201757d406caa31de7ac2f6f063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":113},
                "size":{
                  "width":82,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35f1b1191a354df481f12ce222eae490",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":115},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/01_-_金币任务/u14_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/01_-_金币任务/u14_line.png"}},
{
          "id":"141da355fd7b429aa070a1265a0f6ac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":370,
              "y":147},
            "size":{
              "width":360,
              "height":574}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48662ef3b3ef4e4882f20db600b01f2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":370,
                  "y":147},
                "size":{
                  "width":360,
                  "height":574}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-06_游戏活动快讯分享页面/u20.png"}},
{
          "id":"162759a09e68474080249d64ffceecd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":384,
              "y":254},
            "size":{
              "width":316,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c4d5a00539a4cf29917efc1da74acc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":384,
                  "y":254},
                "size":{
                  "width":316,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0da0986fc3814d0b9a4d80822aca7e0a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":301},
            "size":{
              "width":349,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/03-01__活动首页最新/u147_line.png"}},
{
          "id":"a5baac2263514267a62175c518dbbe65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":390,
              "y":277},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6870ce4514d14203a14a8803e95bab7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":277},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35676c6ec8b842bcaa6389f663f9f93f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":384,
              "y":324},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6a6d4301e194d17bc619a31d9b9d17e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":384,
                  "y":324},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99bd96a758054a4eb33e27857b3f4359",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":164},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c7d72904d3844ed9d650ddf4b1c4a6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":164},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-01__活动首页最新/u59.png"}},
{
          "id":"b9d5ed471fd346a0862b643fcdbbf06e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":447,
              "y":164},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f13373c4f282430b8d974c3bb0dd3968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":447,
                  "y":164},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14e17823635c4102bfbacc270bd8a853",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":447,
              "y":186},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46d09e13cc3b45fe9fb1ca83713449f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":447,
                  "y":186},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8bc08010d0748138c09da3a2463810d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":620,
              "y":170},
            "size":{
              "width":97,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"c9d6d432ad4c4235ac569b445ef3a189",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":219},
            "size":{
              "width":349,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/03-01__活动首页最新/u147_line.png"}},
{
          "id":"90453767c1c94b34bab411d032895f40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":447,
              "y":203},
            "size":{
              "width":143,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d8bc7feecad442fb39b0332e1c37315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":447,
                  "y":203},
                "size":{
                  "width":143,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25d52669778a4bda90a5b6387679cc5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":890,
              "y":190},
            "size":{
              "width":270,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"272fb0c628d64dc19fced45ba97166ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":890,
                  "y":190},
                "size":{
                  "width":270,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/03-06_游戏活动快讯分享页面/u39.png"}},
{
          "id":"5437f7c6f9da4c1b9fd111622cea496f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":894,
              "y":148},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f55c418c689e45ea8dff03446c43a4c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":894,
                  "y":148},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb84c9ce6d504f2d87a60ebb1757b2e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":896,
              "y":205},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6484ade46dc543be8ddd8232ba79d10b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":896,
                  "y":205},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f39d896782af4404b44cc416078cb046",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":894,
              "y":226},
            "size":{
              "width":246,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/03-05_官方活动分享页面/u120_line.png"}},
{
          "id":"ef759b1ed48b464fa702b9e1bc4cfd0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":905,
              "y":226},
            "size":{
              "width":245,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d34b48e7e624bea9d71d57ac877ecf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":905,
                  "y":226},
                "size":{
                  "width":245,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8da4e139f4b940699d4e1ac7508ee5d2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":910,
              "y":286},
            "size":{
              "width":95,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b2854b41a4d34106824190acbf747624",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":1026,
              "y":286},
            "size":{
              "width":106,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3b10acd5961048948e3e6fa40a825399",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":758,
              "y":199},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34ec11ac347f4b8ab85a9af192e959b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":758,
                  "y":199},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"6eab4566280f400faf1a58706740f207",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":764,
              "y":176},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe0e9bbdd084e2e9436cf1d7ecbd04d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":764,
                  "y":176},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "14f7fa0e12e34a0f8729b3e0c967e282":{
      "packageId":"14f7fa0e12e34a0f8729b3e0c967e282",
      "type":"Axure:Master",
      "name":"手机页面",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f7e362c1ebb64abba65417a3e501d81e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":360,
                "height":620}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa9e9c79cac24b7fa17ec805602a905f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":360,
                    "height":620}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/02-_签到/u1.png"}}]}}},
  "objectPaths":{
    "8e77826aff334830a085744f5cec193a":{
      "scriptId":"u0"},
    "14519abc80044504b4462caf129ed963":{
      "scriptId":"u1"},
    "6ad7c3cc427b4b6285ebc8cf2e0a069d":{
      "scriptId":"u2"},
    "a2b8fb0fe63741fda77130b16913d468":{
      "scriptId":"u3"},
    "68c9906d652949718d74d6f042873ba3":{
      "scriptId":"u4"},
    "85516b7c178d42a6a427f7a77ba94aec":{
      "scriptId":"u5"},
    "455c2bb00df1447c942844465fad8d50":{
      "scriptId":"u6"},
    "7615a15fc49745ee8531c98e98342574":{
      "scriptId":"u7"},
    "d2ef94b0d602408795e5b8b1c6f4a60e":{
      "scriptId":"u8"},
    "47bcefa4a8d444e9ad40c2fe9dd5683e":{
      "scriptId":"u9"},
    "8035931d1b5f41968dbb528d6913900d":{
      "scriptId":"u10"},
    "af0e62bec45c43158a211839b62d781b":{
      "scriptId":"u11"},
    "913355b1b7e744f493853422a98e279c":{
      "scriptId":"u12",
      "f7e362c1ebb64abba65417a3e501d81e":{
        "scriptId":"u13"},
      "fa9e9c79cac24b7fa17ec805602a905f":{
        "scriptId":"u14"}},
    "eaae753b5b954440bf3bc4b0a74eb713":{
      "scriptId":"u15"},
    "209da9a4aa0a469b874815261ce8c9b3":{
      "scriptId":"u16"},
    "b32bda89f5d047508efea20e38c584f1":{
      "scriptId":"u17"},
    "a0ee1201757d406caa31de7ac2f6f063":{
      "scriptId":"u18"},
    "35f1b1191a354df481f12ce222eae490":{
      "scriptId":"u19"},
    "141da355fd7b429aa070a1265a0f6ac2":{
      "scriptId":"u20"},
    "48662ef3b3ef4e4882f20db600b01f2d":{
      "scriptId":"u21"},
    "162759a09e68474080249d64ffceecd7":{
      "scriptId":"u22"},
    "9c4d5a00539a4cf29917efc1da74acc1":{
      "scriptId":"u23"},
    "0da0986fc3814d0b9a4d80822aca7e0a":{
      "scriptId":"u24"},
    "a5baac2263514267a62175c518dbbe65":{
      "scriptId":"u25"},
    "6870ce4514d14203a14a8803e95bab7d":{
      "scriptId":"u26"},
    "35676c6ec8b842bcaa6389f663f9f93f":{
      "scriptId":"u27"},
    "e6a6d4301e194d17bc619a31d9b9d17e":{
      "scriptId":"u28"},
    "99bd96a758054a4eb33e27857b3f4359":{
      "scriptId":"u29"},
    "8c7d72904d3844ed9d650ddf4b1c4a6e":{
      "scriptId":"u30"},
    "b9d5ed471fd346a0862b643fcdbbf06e":{
      "scriptId":"u31"},
    "f13373c4f282430b8d974c3bb0dd3968":{
      "scriptId":"u32"},
    "14e17823635c4102bfbacc270bd8a853":{
      "scriptId":"u33"},
    "46d09e13cc3b45fe9fb1ca83713449f4":{
      "scriptId":"u34"},
    "b8bc08010d0748138c09da3a2463810d":{
      "scriptId":"u35"},
    "c9d6d432ad4c4235ac569b445ef3a189":{
      "scriptId":"u36"},
    "90453767c1c94b34bab411d032895f40":{
      "scriptId":"u37"},
    "3d8bc7feecad442fb39b0332e1c37315":{
      "scriptId":"u38"},
    "25d52669778a4bda90a5b6387679cc5b":{
      "scriptId":"u39"},
    "272fb0c628d64dc19fced45ba97166ea":{
      "scriptId":"u40"},
    "5437f7c6f9da4c1b9fd111622cea496f":{
      "scriptId":"u41"},
    "f55c418c689e45ea8dff03446c43a4c4":{
      "scriptId":"u42"},
    "cb84c9ce6d504f2d87a60ebb1757b2e2":{
      "scriptId":"u43"},
    "6484ade46dc543be8ddd8232ba79d10b":{
      "scriptId":"u44"},
    "f39d896782af4404b44cc416078cb046":{
      "scriptId":"u45"},
    "ef759b1ed48b464fa702b9e1bc4cfd0a":{
      "scriptId":"u46"},
    "0d34b48e7e624bea9d71d57ac877ecf7":{
      "scriptId":"u47"},
    "8da4e139f4b940699d4e1ac7508ee5d2":{
      "scriptId":"u48"},
    "b2854b41a4d34106824190acbf747624":{
      "scriptId":"u49"},
    "3b10acd5961048948e3e6fa40a825399":{
      "scriptId":"u50"},
    "34ec11ac347f4b8ab85a9af192e959b8":{
      "scriptId":"u51"},
    "6eab4566280f400faf1a58706740f207":{
      "scriptId":"u52"},
    "6fe0e9bbdd084e2e9436cf1d7ecbd04d":{
      "scriptId":"u53"}}});